### ISSUE TITLE
fiximports.py shouldn't rewrite the file when it doesn't change it

### ISSUE THREAD

**Issue by Callek** [mozilla/build-relengapi-skeleton#2]
In testing I have the case where I get "file was modified..." warnings when I have an editor open and I run validate.sh.

We should adjust fiximports.py to not do an open(.., 'w') unless it needs to.  CC: @tardyp who may be interested in backporting this change elsewhere.

**Comment by djmitche** [comment]
This issue was moved to mozilla/build-relengapi#276
